luohuo:
  cache:
    type: REDIS
    serializer-type: JACK_SON
  redis:
    ip: 10.10.10.78
    port: 16379
    password: luo.123456
    database: 1
spring:
  cache:
    type: GENERIC
  data:
    redis:
      host: ${luohuo.redis.ip}
      password: ${luohuo.redis.password}
      port: ${luohuo.redis.port}
      database: ${luohuo.redis.database}
